import { test } from 'node:test';
import assert from 'node:assert/strict';
import { ErEnv } from '../src/gym/env.js';
import { OraclePolicy } from '../src/gym/oracle.js';
import { getScenario } from '../src/scenarios/index.js';

/**
 * The oracle is the benchmark's ceiling. These are the invariants that make the
 * normalised score mean anything — if one inverts, every reported score is
 * garbage, so they are tests rather than assumptions.
 */

function runOracle(scenario: string, seed = 'oracle-test') {
  const env = new ErEnv(getScenario(scenario), seed);
  const o = new OraclePolicy(env);
  let done = false;
  while (!done) done = env.step(o.act()).done;
  return env;
}

function runNull(scenario: string, seed = 'oracle-test') {
  const env = new ErEnv(getScenario(scenario), seed);
  let done = false;
  while (!done) done = env.step([]).done;
  return env;
}

test('the oracle beats doing nothing in every scenario', () => {
  // The single load-bearing invariant. The normalised score divides by
  // (oracle - null); if that span is not positive the score is meaningless.
  for (const s of ['ed-baseline', 'boarding-crisis', 'understaffed-nights', 'respiratory-season', 'mass-casualty']) {
    const o = runOracle(s).components.total;
    const n = runNull(s).components.total;
    assert.ok(o > n, `${s}: oracle ${Math.round(o)} must beat null ${Math.round(n)}`);
  }
});

test('the oracle saves lives relative to doing nothing', () => {
  for (const s of ['ed-baseline', 'respiratory-season']) {
    const o = runOracle(s).metrics().clinical.deaths;
    const n = runNull(s).metrics().clinical.deaths;
    assert.ok(o < n, `${s}: oracle deaths ${o} must be below null deaths ${n}`);
  }
});

test('the oracle commits no avoidable safety floors on a normal shift', () => {
  const env = runOracle('ed-baseline');
  const safety = env.metrics().safety;
  // Every floor here is avoidable with perfect information EXCEPT
  // wrong-patient-identity, which is generated by task-switching under
  // saturated attention — that one is the environment being genuinely hard,
  // not the policy being careless.
  for (const [kind, n] of Object.entries(safety)) {
    if (kind === 'wrong-patient-identity') continue;
    assert.equal(n, 0, `oracle committed an avoidable floor: ${kind} x${n}`);
  }
});

test('the oracle is deterministic', () => {
  const a = runOracle('ed-baseline', 'det').components.total;
  const b = runOracle('ed-baseline', 'det').components.total;
  assert.equal(a, b);
});

test('the oracle still cannot beat the downstream release process', () => {
  // The Module 1 thesis: even perfect information cannot make a bed appear.
  // If the oracle ever showed near-zero boarding in the crisis scenario, the
  // exogenous release process would not be binding and the scenario would be
  // testing nothing.
  const env = runOracle('boarding-crisis');
  const m = env.metrics();
  if (m.boarding.boarderCount > 0) {
    assert.ok(
      (m.boarding.boardingHoursMean ?? 0) > 0.5,
      'boarding must remain costly for the oracle — the upstream is unfixable in Module 1',
    );
  }
});

test('the oracle orders the workup that matches the condition', () => {
  const env = runOracle('ed-baseline');
  // A STEMI patient must have had cardiology/troponin/aspirin ordered — the
  // pathway that was dead until the Math.floor fix.
  const stemi = [...env.patients.values()].filter((p) => p.latent.condition === 'stemi' && p.orders.length > 0);
  if (stemi.length === 0) return;
  const names = new Set(stemi.flatMap((p) => p.orders.map((id) => env.orders.get(id)?.name)));
  assert.ok(
    names.has('troponin') || names.has('aspirin') || names.has('cardiology'),
    `oracle ordered nothing on the STEMI pathway: ${[...names].join(', ')}`,
  );
});
